import dotenv from "dotenv";

dotenv.config();

export const config : Record<string, any> = {
  MUMBAI_POLYGONSCAN_API_URL: process.env.MUMBAI_POLYGONSCAN_API_URL,
  MUMBAI_POLYGONSCAN_API_KEY: process.env.MUMBAI_POLYGONSCAN_API_KEY,
  MUMBAI_ROOT_PRIVATE_KEY: process.env.MUMBAI_ROOT_PRIVATE_KEY,
  MUMBAI_ROOT_ADDRESS: process.env.MUMBAI_ROOT_ADDRESS,
  MUMBAI_RPC_URL: process.env.MUMBAI_RPC_URL,
  POLYGON_POLYGONSCAN_API_URL: process.env.POLYGON_POLYGONSCAN_API_URL,
  POLYGON_POLYGONSCAN_API_KEY: process.env.POLYGON_POLYGONSCAN_API_KEY,
  POLYGON_DEPLOYER_PRIVATE_KEY: process.env.POLYGON_DEPLOYER_PRIVATE_KEY,
  POLYGON_DEPLOYER_ADDRESS: process.env.POLYGON_DEPLOYER_ADDRESS,
  POLYGON_RPC_URL: process.env.POLYGON_RPC_URL,
  REPORT_GAS: process.env.REPORT_GAS || false,
};

export default config;
